### ISSUE TITLE
Malicia walks very fast on Steam.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#407] opened 2018-10-20 09:39 UTC
https://streamable.com/q2awk
https://streamable.com/7lgmr
https://streamable.com/3z5fk  (regson)

**Comment by cigumo** [comment] 2018-10-22 19:46
I cannot reproduce it. 
Tried alone and combinations of: 
- scourger lash
- forest keepers vine
- bravebark ultimate (levels 3 and 5)

If anybody can reproduce it please let me know!!
A sshot of the tower setup will also be helpful.

**Comment by cigumo** [comment] 2018-11-28 21:19
Also happened to VirtualTT and SealDarkLight
![turbo_malicia](https://user-images.githubusercontent.com/934821/49182818-0c035d80-f33a-11e8-9eec-a9bb14712b08.gif)

**Comment by guaranteed-to-be-unique** [comment] 2019-01-11 20:17
My tower setup: Wild Magus - Eldrich Doom, Weirdwood - both upgrades maxed, Forest Keepers - spear and heal maxed, Golden Longbows - both upgrades, but not maxed, gnomes - all maxed. Also I should mention that speedup seem to happen only after Malicia retreats and returns back. At least I've never seen it happening during initial encounter.
![2019-01-11_230806](https://user-images.githubusercontent.com/22380626/51057341-5c86ff80-15f6-11e9-9adf-3af9433590c7.jpg)

**Comment by cigumo** [comment] 2019-02-12 19:34
Is it related to gnomes??
Happened to me with gloomies too

**Comment by cigumo** [comment] 2019-02-12 21:08
found!!! yes! 
fixed in 1.4.1-alpha-31

**Closed as completed by cigumo** 2019-02-12 21:08 UTC
Labels: n.feedback, 1.PRIO.HIGH, g.kr3
