### ISSUE TITLE
 Executioner image for notification balloon is cut at the top / DancheZI

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1039] opened 2019-12-02 15:02 UTC
Love mobile
![Screenshot_2019-12-02_235951](https://user-images.githubusercontent.com/43391939/69969629-2204b900-1560-11ea-90ae-f60a10971b61.jpg)

Cocos
![Screenshot_2019-12-03_001502](https://user-images.githubusercontent.com/43391939/69970814-3b0e6980-1562-11ea-8973-e08d3a40cf5c.jpg)

**Comment by cigumo** [comment] 2019-12-10 21:25
that's not a bug actually. 
texts were removed from the mobile version due to i18n issues.

**Comment by sunnydaler** [comment] 2019-12-11 01:53
I misunderstood DancheZI's point. He pointed out that the top of the image inside the circle is cut.
For comparison;
![20191211_105445](https://user-images.githubusercontent.com/43391939/70584477-a90efc80-1c04-11ea-87f1-cc5247d35cb0.jpg)

**Comment by cigumo** [comment] 2019-12-11 17:28
ah! ok :D
there are a few others too

**Comment by cigumo** [comment] 2019-12-11 17:36
![alert_creep_0005](https://user-images.githubusercontent.com/934821/70645325-90620f00-1c23-11ea-8666-94ec10bc6a02.png)
![alert_creep_0046](https://user-images.githubusercontent.com/934821/70645359-9ce66780-1c23-11ea-9b22-d402e3cb5e7e.png)
![alert_creep_0049](https://user-images.githubusercontent.com/934821/70645371-a1ab1b80-1c23-11ea-9c63-89e902c64fcc.png)

**Comment by cigumo** [comment] 2019-12-11 17:39
fixed in kr2-phone-3.2.16

**Closed as completed by cigumo** 2019-12-11 17:39 UTC
Labels: z.wontfix, t.phone, g.kr2
