### ISSUE TITLE
Dragons hourglass times are incorrect

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#1194] opened 2020-02-28 20:14 UTC
Ashbite (Hourglass: Normal) 
Bonehart (Hourglass: Slow)

it would be great if we could really calculate it and not just leave it as hard text.

http://support.ironhidegames.com/a/tickets/61240

**Comment by sunnydaler** [comment] 2020-02-29 00:05
#805

**Comment by cigumo** [comment] 2020-06-19 16:47
duplicate of #805

**Closed as completed by cigumo** 2020-06-19 16:47 UTC
Labels: z.duplicate, 1.PRIO.LOW, g.kr2
