### ISSUE TITLE
Crashes on kr2 endless

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#1245] opened 2020-03-19 20:56 UTC
At the endless stage of frontiers the game crashes
Phone: samsung s5
Android: 7.0 

![Screenshot_20200318-023015](https://user-images.githubusercontent.com/49003944/77114162-d4c32f00-6a0a-11ea-8729-47e032ba6635.png)

**Comment by victoriadelima** [comment] 2020-03-19 20:56
http://support.ironhidegames.com/a/tickets/61728

**Comment by cigumo** [comment] 2020-06-19 16:49
pretty sure it's a duplicate of #836 referring to KR3 instead.

**Closed as completed** 2020-06-19 16:51 UTC
Labels: g.kr2
