### ISSUE TITLE
Hero barmeter stats change after playing

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1266] opened 2020-03-25 20:32 UTC
it happened to Elora and Hacksaw.

one way to reproduce is..

select elora and enter Forsaken Valley
start the battle and restart 3 times
exit to the world map
 check if her sword barmeter in hero room is not 2 bars.

**Comment by cigumo** [comment] 2020-03-26 02:42
can't reproduce it, mabye fixed with #1260

**Comment by sunnydaler** [comment] 2020-03-27 17:57
not fixed still.

**Comment by cigumo** [comment] 2020-04-28 22:21
I still can't reproduce :(

**Comment by cigumo** [comment] 2020-05-12 13:51
fixed in desktop and console 4.2.12

**Closed as completed by cigumo** 2020-05-12 13:51 UTC
Labels: n.feedback, g.kr1
