### ISSUE TITLE
kr1: Fungal Forest middle path wave icon displayed on the left

### ISSUE THREAD

**Issue by Mmlh1** [cigumo/krli#1389] opened 2020-05-18 20:52 UTC
https://cdn.discordapp.com/attachments/212252625792532480/712042924522864720/Screenshot_20200518-224258.png

The Swamp Things go over the middle path, but are displayed on the left.

**Comment by cigumo** [comment] 2020-05-19 02:42
duplicate of #1390

**Closed as completed by cigumo** 2020-05-19 02:42 UTC
