### ISSUE TITLE
After completing the level 12

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1131] opened 2020-02-07 04:04 UTC
Here's a screenshot of the Love map captured right after the Dark Tower campaign is completed.
(video is here https://streamable.com/dzbp2         )
![20200207125612_1](https://user-images.githubusercontent.com/43391939/74002765-8f472700-49b3-11ea-894f-a1eb33a59086.jpg)

and below is Unity version's screenshot captured right after the Dark Tower campaign is completed.
![unity](https://user-images.githubusercontent.com/43391939/74003297-763f7580-49b5-11ea-98a1-309a1c64a0da.jpg)

- [x] unlocked levels
1. "Pandaemonium" is unlocked, instead of "Pit of Fire".
2. "Ha'Kraj Plateau" is unlocked, instead of "Glacial Heights".
3. Ruins of Acaroth (stage 14), Rotten Forest, and Rotwick are not unlocked.
-Ruins of Acaroth is unlocked after the Sarelgaz's Lair is completed. 
-Rotten Forest is unlocked after the Ruins of Acaroth is completed.

- [ ] Even after the stage is beaten in veteran mode, Great Defender and Supreme Defender achievements don't pop up. Besides, Supreme Defender is shown as not achieved yet in the Achievements room.
![20200209024939_1](https://user-images.githubusercontent.com/43391939/74089667-f74a5a00-4ae6-11ea-9878-5bdd5a7f3544.jpg)

- [ ] Even after all Heroic and Iron missions from stage 1 to 12 are completed, Heroic Defender and Iron Defender achievements don't pop up. They are still grayed out in the achievements room. 

- [x]  In unity, the dotted line links "dark tower" and "pit of fire" (Pandaemonium on love). When the pit of fire is not a part of main campaigns, is it necessary?

**Comment by cigumo** [comment] 2020-02-11 22:44
fixed in 4.0.07
-  Supreme Defender not working
- level unlock sequence
- road animation going past veznan's castle

could not reproduce the other issues about the achievements. they work for me.

**Closed as completed by cigumo** 2020-02-11 22:44 UTC
Labels: 1.PRIO.HIGH, g.kr1
