### ISSUE TITLE
testla´s towers efect not vanishing

### ISSUE THREAD

**Issue by victoriadelima** [cigumo/krli#910] opened 2019-10-17 12:01 UTC
The efect effect don't vanish after a short while. 

![Screenshot_20191017-002642](https://user-images.githubusercontent.com/49003944/67006939-a1c3ea80-f0bc-11e9-9b4c-1a4529541b1b.png)

http://support.ironhidegames.com/a/tickets/58242

**Comment by victoriadelima** [comment] 2019-10-17 12:02
http://support.ironhidegames.com/a/tickets/58053

**Comment by victoriadelima** [comment] 2019-10-17 12:02
http://support.ironhidegames.com/a/tickets/58051

**Comment by cigumo** [comment] 2019-10-17 12:46
duplicate of #898

**Closed as completed by cigumo** 2019-10-17 12:46 UTC
Labels: t.phone, g.kr2
