### ISSUE TITLE
Review spawns in Bonesburg Heroic wave 6.

### ISSUE THREAD

**Issue by sunnydaler** [cigumo/krli#1023] opened 2019-11-28 02:43 UTC
When the moon hits in wave 6,
zombies should spawn from various places.
![20191128113902_1](https://user-images.githubusercontent.com/43391939/69772777-32213f00-11d4-11ea-978c-f1a7e25566f4.jpg)

**Comment by cigumo** [comment] 2019-11-28 13:57
love: https://streamable.com/uxtxn
cocos: https://streamable.com/272yo

**Comment by sunnydaler** [comment] 2019-11-28 16:11
https://streamable.com/wkrlo Zero spawn on love.

**Comment by cigumo** [comment] 2019-11-28 16:25
sunnydaler: https://streamable.com/wkrlo Zero spawn on love.

**Comment by cigumo** [comment] 2019-11-28 16:25
I can't reproduce the zero spawns bug.

**Comment by sunnydaler** [comment] 2019-11-30 00:08
it looks to work only in debug build.
zero spawn in all love gameplays I found on youtube.
https://youtu.be/giXXsLuk0bQ?t=378 (6:18)
https://youtu.be/Vi_VFEOsPhM?t=662 (11:02)
https://youtu.be/k4HL9Ts57RU?t=643 (10:45)
https://youtu.be/x65UFaSRfZc?t=461 (7:44)
https://youtu.be/GxEs_r1bUEo?t=496 (8:17)
https://youtu.be/psXo4hqCH7w?t=2797 (46:41)
https://youtu.be/IfIddVciMqQ?t=658 (11:02)
https://youtu.be/6f7PFxEX9Hc?t=328 (5:30)

**Comment by cigumo** [comment] 2019-12-03 13:00
fixed in kr2-desktop-3.2.13

**Closed as completed by cigumo** 2019-12-03 13:00 UTC
Labels: g.kr2
